### PR TITLE
Rename event_stack to segment_stack on ActiveStorageSubscriber

### PR DESCRIPTION
**Pull request by meacuna**
I believe that 0f670cca introduced an error on `ActiveStorageSubscriber`. I'm getting the following error after I updated from version 6.2.0 to 6.4.0.
```
ERROR : NameError: undefined local variable or method 'event_stack' for #<NewRelic::Agent::Instrumentation::ActiveStorageSubscriber:0x0000561d177276f0>
```

### CODE REVIEW

**Comment by mwear** [comment]
Hi @meacuna. We appreciate you fixing this, but we are already aware of the issue and have fixed it in our development branch, otherwise we'd gladly accept this PR. We will be pushing out the fix soon. In the meantime, you can use version 6.3.0 of the agent.

**Comment by meacuna** [comment]
That's great, thanks for the information.

**Comment by MSeneadza** [comment]
Good to know the fix is coming.  I just got hit by this.
