### PR TITLE
Fix test errors caused by 585f07e

### PR DESCRIPTION
**Pull request by jrmhaig**
When upgrading to use `newrelic_rpm` version 4.5.0.337 our unit tests result in a large number of errors mostly like:

```
ActiveRecord::RecordInvalid: Validation failed: Branch must exist
```

There are a few others but this error is by far the largest in number. I have identified the commit that causes this (https://github.com/newrelic/rpm/commit/704fe528c245b90acfd71358a6b3928b8076372e) and I notice that the code that is moved from the end to the start of the block is also moved outside of the `ActiveSupport.on_load(:active_record) do` block. These lines have subsequently been changed into a single line:

```
::NewRelic::Agent::PrependSupportability.record_metrics_for(::ActiveRecord::Base, ::ActiveRecord::Relation)
```

If I move this back inside the `on_load` block then all our tests run without error.

I am raising a PR as I am unable to create an issue. I realise that this may not be a complete fix as other things may be affected but it prevents the test errors we are seeing so it is at least moving towards a fix.

### CODE REVIEW

**Comment by bnaysakya** [comment]
@jrmhaig coming from [this](https://discuss.newrelic.com/t/newrelic-rpm-throws-error-in-consume-message-headers/52736) issue, I downgraded newrelic_rpm to **4.3.0.335** but still I'm getting:
```
ERROR : Error in consume_message_headers
ERROR : NoMethodError: undefined method `[]' for nil:NilClass
```
But, using **newrelic_rpm** to **3.16**  solved this issue for me.

**Comment by danascheider** [comment]
@jrmhaig Thank you so much for putting in the time and effort to make New Relic better for everyone! We've merged your code and are going to be releasing it in version 4.7. 

Incidentally, the `NoMethodError`s you're seeing are not related to this issue at all - they're related to a bug in our RabbitMQ instrumentation that will also be fixed in the upcoming release.

Thanks again for your work on this!

**Comment by mwear** [comment]
Thanks for the contribution @jrmhaig . Your changes are part of Ruby Agent version 4.7.0.339 which was released on 12/19.
